FROM python:3.10-slim

WORKDIR /app

COPY . /app

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY . .

COPY start-celery.sh /app/start-celery.sh

RUN chmod +x /app/start-celery.sh

CMD ["./start-celery.sh"]